const sections = [
  {
    id: "intro",
    name: "Intro",
    start_bar: 1,
    end_bar: 8,
    energy: 25,
    density: "Low",
    intent: "Set the dusty cinematic tone",
    transition_in: "Clean start",
    transition_out: "Small lift into verse",
  },
  {
    id: "verse_1",
    name: "Verse 1",
    start_bar: 9,
    end_bar: 24,
    energy: 55,
    density: "Medium",
    intent: "Establish groove and vocal space",
    transition_in: "Rhythm entry",
    transition_out: "Lift into hook",
  },
  {
    id: "hook",
    name: "Hook",
    start_bar: 25,
    end_bar: 32,
    energy: 82,
    density: "High",
    intent: "Deliver emotional peak",
    transition_in: "Strong arrival",
    transition_out: "Drop back to verse",
  },
  {
    id: "verse_2",
    name: "Verse 2",
    start_bar: 33,
    end_bar: 48,
    energy: 62,
    density: "Medium",
    intent: "Develop the groove with subtle variation",
    transition_in: "Reduced re-entry",
    transition_out: "Build into bridge",
  },
  {
    id: "bridge",
    name: "Bridge",
    start_bar: 49,
    end_bar: 56,
    energy: 42,
    density: "Low",
    intent: "Create contrast and space",
    transition_in: "Filtered reset",
    transition_out: "Riser into final hook",
  },
  {
    id: "final_hook",
    name: "Final Hook",
    start_bar: 57,
    end_bar: 72,
    energy: 92,
    density: "High",
    intent: "Full arrangement payoff",
    transition_in: "Maximum lift",
    transition_out: "Release into outro",
  },
  {
    id: "outro",
    name: "Outro",
    start_bar: 73,
    end_bar: 80,
    energy: 28,
    density: "Low",
    intent: "Let the atmosphere decay",
    transition_in: "Energy release",
    transition_out: "Clean ending",
  },
];

function createTrack({
  id,
  name,
  type,
  role,
  targetGenerator,
  activeSections,
  mutedSections,
  density,
  groove,
  variation,
  transition,
  movement,
  sound,
  routing,
  metadata,
  energyProfile,
}) {
  return {
    id,
    name,
    type,
    role,
    target_generator: targetGenerator,
    active_sections: activeSections,
    muted_sections: mutedSections,
    density_profile: density,
    energy_profile: energyProfile,
    groove_profile: groove,
    variation_plan: variation,
    transition_plan: transition,
    automation_intent: movement,
    sound_source_intent: sound,
    routing_intent: routing,
    planning_metadata: metadata,
    generator_payload: {
      job_intent: `Prepare ${name.toLowerCase()} direction`,
      bar_scope: "1-80",
      constraints: ["High-level production guidance only"],
    },
  };
}

export function createMockBlueprint() {
  const blueprint = {
    project: {
      id: "babasultan_night_drive",
      name: "BabaSultan Night Drive",
      bpm: 95,
      key: "D",
      scale: "Minor",
      time_signature: "4/4",
      total_bars: 80,
      groove_profile: "Boom Bap Swing",
      swing_amount: 58,
      mood: "Emotional / Dusty / Cinematic",
      genre_tags: ["boom bap", "arabesk", "cinematic"],
    },
    daw: {
      target_daw: "Ableton Live",
      sample_rate: 48000,
      bit_depth: 24,
      global_quantization: "1 Bar",
      launch_mode: "Arrangement View",
      locator_markers: sections.map((section) => ({
        section_id: section.id,
        name: section.name,
        bar: section.start_bar,
      })),
      tempo_automation_allowed: false,
      return_tracks: [
        { id: "return_space", name: "Space", intent: "Controlled cinematic depth" },
        { id: "return_texture", name: "Texture", intent: "Dust and tape character" },
      ],
      master_chain_intent: "Warm, controlled, and song-ready",
    },
    arrangement: {
      sections,
    },
    tracks: [
      createTrack({
        id: "track_drums",
        name: "Drums",
        type: "midi",
        role: "Rhythm Foundation",
        targetGenerator: "drum_generator",
        activeSections: ["verse_1", "hook", "verse_2", "bridge", "final_hook"],
        mutedSections: ["intro", "outro"],
        density: "Verse: Medium / Hook: High",
        groove: "Heavy Swing",
        variation: "Progressive fills",
        transition: "Lift hooks, reduce bridge",
        movement: "Controlled verses, stronger hooks, reduced bridge/outro.",
        sound: "Dusty Boom Bap Kit",
        routing: "Drums grouped for warm parallel character",
        metadata: {
          Groove: "Heavy Swing",
          Swing: "58%",
          Kit: "Dusty Boom Bap",
          Feel: "Humanized",
          Fills: "Hook Lifts",
          Range: "Controlled",
        },
        energyProfile: { intro: 0, verse_1: 55, hook: 85, verse_2: 62, bridge: 35, final_hook: 92, outro: 0 },
      }),
      createTrack({
        id: "track_bass",
        name: "Bass",
        type: "midi",
        role: "Low-End Support",
        targetGenerator: "bass_generator",
        activeSections: ["verse_1", "hook", "verse_2", "final_hook"],
        mutedSections: ["intro", "bridge", "outro"],
        density: "Verse: Medium / Hook: High",
        groove: "Pocketed",
        variation: "Hook emphasis",
        transition: "Simplify before lifts",
        movement: "Low-end support enters after intro, stronger in hooks, simplified in bridge.",
        sound: "Warm Analog Bass",
        routing: "Focused low-end with clean center weight",
        metadata: {
          Character: "Warm Analog",
          Weight: "Deep",
          Movement: "Pocketed",
          Register: "Low-Mid",
          Hook: "Strong",
          Sustain: "Short",
        },
        energyProfile: { intro: 0, verse_1: 55, hook: 84, verse_2: 64, bridge: 0, final_hook: 90, outro: 0 },
      }),
      createTrack({
        id: "track_chords",
        name: "Chords",
        type: "midi",
        role: "Harmonic Bed",
        targetGenerator: "chord_generator",
        activeSections: ["intro", "verse_1", "hook", "verse_2", "bridge", "final_hook", "outro"],
        mutedSections: [],
        density: "Verse: Low / Hook: Medium",
        groove: "Laid Back",
        variation: "Texture growth",
        transition: "Widen hooks",
        movement: "Harmonic bed supports intro and bridge, thicker during hooks.",
        sound: "Arabesk Rhodes Pad",
        routing: "Wide harmonic layer with restrained ambience",
        metadata: {
          Style: "Minor Soul",
          Width: "Wide",
          Texture: "Dusty Rhodes",
          Layers: "Two",
          Complexity: "Simple",
        },
        energyProfile: { intro: 30, verse_1: 42, hook: 70, verse_2: 48, bridge: 58, final_hook: 78, outro: 25 },
      }),
      createTrack({
        id: "track_melody",
        name: "Melody",
        type: "audio_or_midi",
        role: "Lead Identity",
        targetGenerator: "sample_generator",
        activeSections: ["intro", "hook", "bridge", "final_hook", "outro"],
        mutedSections: ["verse_1", "verse_2"],
        density: "Hook: Medium / Bridge: Low",
        groove: "Loose",
        variation: "Motif repeats",
        transition: "Answer hooks",
        movement: "Lead identity appears in intro and hooks, with space left through verses.",
        sound: "Arabesk Lead Texture",
        routing: "Lead texture sits above chords with soft delay",
        metadata: {
          Identity: "Arabesk Lead",
          Motif: "Emotional",
          Register: "High-Mid",
          Phrase: "Sparse",
        },
        energyProfile: { intro: 40, verse_1: 0, hook: 76, verse_2: 0, bridge: 50, final_hook: 88, outro: 28 },
      }),
      createTrack({
        id: "track_vocal",
        name: "Vocal",
        type: "guide",
        role: "Vocal Space",
        targetGenerator: "vocal_planner",
        activeSections: ["verse_1", "hook", "verse_2", "final_hook"],
        mutedSections: ["intro", "bridge", "outro"],
        density: "Verse: Medium / Hook: High",
        groove: "Human",
        variation: "Hook doubles",
        transition: "Leave bridge open",
        movement: "Verse-focused space with wider hook presence and bridge silence.",
        sound: "BabaSultan Vocal Space",
        routing: "Lead space remains clear and centered",
        metadata: {
          Space: "Wide Hook",
          Verse: "Focused",
          Hook: "Open",
          Adlibs: "Light",
          Silence: "Bridge",
        },
        energyProfile: { intro: 0, verse_1: 68, hook: 86, verse_2: 70, bridge: 0, final_hook: 94, outro: 0 },
      }),
      createTrack({
        id: "track_fx",
        name: "FX",
        type: "audio",
        role: "Atmosphere & Transitions",
        targetGenerator: "fx_generator",
        activeSections: ["intro", "hook", "bridge", "final_hook", "outro"],
        mutedSections: ["verse_1", "verse_2"],
        density: "Transitions: Medium",
        groove: "Floating",
        variation: "Section lifts",
        transition: "Risers and releases",
        movement: "Atmosphere and transitions support section changes without dominating.",
        sound: "Tape Space FX",
        routing: "Atmosphere supports transitions with restrained width",
        metadata: {
          Atmosphere: "Tape Space",
          Transition: "Medium",
          Motion: "Wide",
          Impact: "Soft",
          Build: "Cinematic",
        },
        energyProfile: { intro: 45, verse_1: 18, hook: 70, verse_2: 20, bridge: 60, final_hook: 84, outro: 35 },
      }),
    ],
    generator_jobs: [
      {
        id: "job_drums",
        generator: "Drum Generator",
        target_track: "track_drums",
        target_sections: ["verse_1", "hook", "verse_2", "bridge", "final_hook"],
        priority: "High",
        status: "Waiting",
        payload: { job_type: "Rhythm foundation", bar_range: "9-72", source_track_payload: "Dusty swung drums" },
      },
      {
        id: "job_bass",
        generator: "Bass Generator",
        target_track: "track_bass",
        target_sections: ["verse_1", "hook", "verse_2", "final_hook"],
        priority: "High",
        status: "Waiting",
        payload: { job_type: "Low-end support", bar_range: "9-72", source_track_payload: "Warm analog bass" },
      },
      {
        id: "job_chords",
        generator: "Chord Generator",
        target_track: "track_chords",
        target_sections: ["intro", "verse_1", "hook", "verse_2", "bridge", "final_hook", "outro"],
        priority: "Medium",
        status: "Waiting",
        payload: { job_type: "Harmonic support", bar_range: "1-80", source_track_payload: "Minor Rhodes pad" },
      },
      {
        id: "job_sample",
        generator: "Sample Generator",
        target_track: "track_melody",
        target_sections: ["intro", "hook", "bridge", "final_hook", "outro"],
        priority: "Medium",
        status: "Waiting",
        payload: { job_type: "Lead texture", bar_range: "1-80", source_track_payload: "Arabesk melodic motif" },
      },
      {
        id: "job_fx",
        generator: "FX Generator",
        target_track: "track_fx",
        target_sections: ["intro", "hook", "bridge", "final_hook", "outro"],
        priority: "Medium",
        status: "Waiting",
        payload: { job_type: "Transitions", bar_range: "1-80", source_track_payload: "Tape space and risers" },
      },
      {
        id: "job_vocal",
        generator: "Vocal Planner",
        target_track: "track_vocal",
        target_sections: ["verse_1", "hook", "verse_2", "final_hook"],
        priority: "Medium",
        status: "Waiting",
        payload: { job_type: "Vocal space", bar_range: "9-72", source_track_payload: "Verse and hook guide" },
      },
    ],
    export_targets: {
      ableton_builder: { enabled: true, payload_roots: ["project", "daw", "arrangement", "tracks"] },
      drum_generator: { enabled: false, payload_roots: [] },
      bass_generator: { enabled: false, payload_roots: [] },
      chord_generator: { enabled: false, payload_roots: [] },
      fx_generator: { enabled: false, payload_roots: [] },
      vocal_planner: { enabled: false, payload_roots: [] },
    },
    production_log: [
      { type: "complete", message: "Prompt received" },
      { type: "complete", message: "Mock blueprint generated" },
      { type: "complete", message: "Arrangement created" },
      { type: "pending", message: "Waiting for local generators" },
    ],
  };

  return blueprint;
}
